GeneralMagicio/pairwise-RPGF4

src/app/badges/components/BadgeCard.tsx
src/app/badges/page.tsx
src/app/components/CollectVotingPowerContent.tsx

Add new badge information

---

src/app/categories/[categoryId]/pairwise-ranking/ranking-list/edit/page.tsx
src/app/categories/[categoryId]/project-ranking/edit/page.tsx

Disable edit with no changes

---

src/app/categories/[categoryId]/page.tsx
src/app/categories/[categoryId]/project-ranking/page.tsx
src/app/components/CollectVotingPowerContent.tsx

Fix minor bugs

---

src/app/categories/[categoryId]/pairwise-ranking/ranking-list/edit/page.tsx

fix reorder issue

---

src/app/categories/[categoryId]/project-ranking/done/page.tsx
src/app/categories/[categoryId]/project-ranking/page.tsx
src/app/category-ranking/components/CategoryPairwiseModal.tsx

made appropriate changes

---

src/app/categories/components/CategoryBadge.tsx

changed Category badge colors

---

src/app/categories/[categoryId]/page.tsx

must at least --> must choose at least

---

src/app/connect/components/ConnectErrorBox.tsx
src/app/connect/otp/page.tsx

Otp restructure

---

package.json
src/app/connect/components/ConnectSplashMessage.tsx
src/app/connect/page.tsx
yarn.lock

added splash message for mobile users when /connect

---

src/app/categories/[categoryId]/project-ranking/done/page.tsx

added now at begining

---

src/app/components/ConnectDrawers.tsx
src/app/connect/components/ConnectButton.tsx

Added need help button so people can join our telegram group for support. (Griff's request)

add need help links

---

src/app/categories/[categoryId]/page.tsx
src/app/components/ConnectWalletContent.tsx
src/app/connect/components/ConnectButton.tsx
src/app/providers/WagmiAppProvider.tsx

Remove extra Metamasks and add hint for using WalletConnect

---

src/app/components/ConnectDrawers.tsx
src/app/components/Header.tsx
src/app/components/LogoutModal.tsx
src/app/providers/ConnectProvider.tsx

Logout modal#109

---

public/images/icons/IconCancel.tsx
src/app/categories/[categoryId]/pairwise-ranking/comment/page.tsx
src/app/categories/[categoryId]/pairwise-ranking/page.tsx
src/app/categories/[categoryId]/pairwise-ranking/ranking-list/edit/page.tsx
src/app/categories/[categoryId]/pairwise-ranking/ranking-list/page.tsx
src/app/categories/components/CategoryItem.tsx
src/app/category-ranking/comment/page.tsx
src/app/category-ranking/page.tsx
src/app/components/TopRouteIndicator.tsx

made UI changes

---

src/app/categories/components/CategoryItem.tsx

changed category description styling

---

src/app/connect/page.tsx

Copy change#181

---

src/app/categories/[categoryId]/pairwise-ranking/page.tsx
src/app/categories/components/CategoryPairwiseCardWithMetrics.tsx
src/app/categories/components/CategoryProjectRankingCardWithMetrics.tsx
tailwind.config.ts

UI fix cotabes phone#180

---

src/utils/getMetrics.ts
src/utils/numbers.ts

Fix some minor metric issues

---

public/images/icons/IconBug.tsx
src/app/components/LogoutModal.tsx
tailwind.config.ts

Fixed logout #192

---

src/app/categories/components/Countdown.tsx
src/app/categories/layout.tsx

Add countdown to the main page

---

src/app/categories/[categoryId]/page.tsx

Sort projects alphabetically#57

---

src/app/components/Header.tsx
src/utils/auth.ts

Different op characters#50

---

src/app/categories/components/CategoryRewardBanner.tsx
src/app/categories/page.tsx

Reward banner#119

---

src/app/categories/[categoryId]/pairwise-ranking/page.tsx
src/app/categories/[categoryId]/project-ranking/page.tsx
src/app/components/ProgressBar.tsx

 added show minimum project color to progress bar

---

src/app/categories/[categoryId]/project-ranking/done/page.tsx
src/app/categories/[categoryId]/project-ranking/edit/page.tsx
src/app/categories/[categoryId]/project-ranking/page.tsx
src/app/categories/[categoryId]/project-ranking/summary/page.tsx
src/app/components/TopNavigation.tsx

https://github.com/user-attachments/assets/50961954-8588-453e-b4b4-aaefd2a062c0

Improvemts finish filtering#225
